### ISSUE TITLE
Wrong handling of string sensor

### ISSUE THREAD

**Issue by h4fn3rb** [killer0071234/ha-hiq#116]
### System Health details

Logger: custom_components.hiq
Source: helpers/update_coordinator.py:290
Integration: HIQ-Home ([documentation](https://github.com/killer0071234/ha-hiq), [issues](https://github.com/killer0071234/ha-hiq/issues))
First occurred: 11:05:07 AM (32 occurrences)
Last logged: 11:15:28 AM

Unexpected error fetching hiq data: Sensor sensor.c13250_sys_ip_port has device class 'None', state class 'None' unit 'None' and suggested precision '0' thus indicating it has a numeric value; however, it has the non-numeric value: '192.168.12.20:8442' (<class 'str'>)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 621, in state
    numerical_value = float(value)  # type:ignore[arg-type]
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: '192.168.12.20:8442'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hiq/coordinator.py", line 68, in _async_update_data
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 469, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 784, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 749, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 623, in state
    raise ValueError(
ValueError: Sensor sensor.c13250_sys_ip_port has device class 'None', state class 'None' unit 'None' and suggested precision '0' thus indicating it has a numeric value; however, it has the non-numeric value: '192.168.12.20:8442' (<class 'str'>)

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/killer0071234/ha-hiq/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Controller model

- [X] Cybro-2
- [ ] Cybro-3

### Describe the issue

Logger: custom_components.hiq
Source: helpers/update_coordinator.py:290
Integration: HIQ-Home ([documentation](https://github.com/killer0071234/ha-hiq), [issues](https://github.com/killer0071234/ha-hiq/issues))
First occurred: 11:05:07 AM (32 occurrences)
Last logged: 11:15:28 AM

Unexpected error fetching hiq data: Sensor sensor.c13250_sys_ip_port has device class 'None', state class 'None' unit 'None' and suggested precision '0' thus indicating it has a numeric value; however, it has the non-numeric value: '192.168.12.20:8442' (<class 'str'>)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 621, in state
    numerical_value = float(value)  # type:ignore[arg-type]
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: '192.168.12.20:8442'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hiq/coordinator.py", line 68, in _async_update_data
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 469, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 784, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 749, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 623, in state
    raise ValueError(
ValueError: Sensor sensor.c13250_sys_ip_port has device class 'None', state class 'None' unit 'None' and suggested precision '0' thus indicating it has a numeric value; however, it has the non-numeric value: '192.168.12.20:8442' (<class 'str'>)

### Reproduction steps

1.Appeared after llast update
2.
3.

### Debug logs

```text
Logger: custom_components.hiq
Source: helpers/update_coordinator.py:290
Integration: HIQ-Home (documentation, issues)
First occurred: 11:05:07 AM (32 occurrences)
Last logged: 11:15:28 AM

Unexpected error fetching hiq data: Sensor sensor.c13250_sys_ip_port has device class 'None', state class 'None' unit 'None' and suggested precision '0' thus indicating it has a numeric value; however, it has the non-numeric value: '192.168.12.20:8442' (<class 'str'>)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 621, in state
    numerical_value = float(value)  # type:ignore[arg-type]
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: '192.168.12.20:8442'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hiq/coordinator.py", line 68, in _async_update_data
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 469, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 784, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 749, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 623, in state
    raise ValueError(
ValueError: Sensor sensor.c13250_sys_ip_port has device class 'None', state class 'None' unit 'None' and suggested precision '0' thus indicating it has a numeric value; however, it has the non-numeric value: '192.168.12.20:8442' (<class 'str'>)
```

**Comment by killer0071234** [comment]
Fixed in next Release.

Thanks for reporting!
