### ISSUE TITLE
Diagnostic sensor for ip port causes all entities in invalid

### ISSUE THREAD

**Issue by killer0071234** [killer0071234/ha-hiq#53]
## System Information

version | core-2023.5.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.11
os_name | Linux
os_version | 6.1.25
arch | x86_64
timezone | Europe/Vienna
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4880
Installed Version | 1.32.1
Stage | running
Available Repositories | 1284
Downloaded Repositories | 10

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 37

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.04.1
agent_version | 1.5.1
docker_version | 23.0.3
disk_total | 30.8 GB
disk_used | 17.9 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.6.0), NGINX Home Assistant SSL proxy (3.4.2), Let's Encrypt (4.12.8), Samba share (10.0.1), ESPHome (2023.4.4), CybroScgiServer (0.1.1), Nginx Proxy Manager (0.12.3), Node-RED (14.1.5), MariaDB (2.6.1), motionEye (0.19.1), RaspberryMatic CCU (3.69.7.20230506), Terminal & SSH (9.7.0), Mosquitto broker (6.2.1), Cloudflared (4.1.5), Duck DNS (1.15.0), Studio Code Server (5.5.7), InfluxDB (4.6.0), Grafana (8.2.2), Zigbee2MQTT (1.30.4-1), Uptime Kuma (0.7.3), Wmbusmeters (W-MBus to MQTT) (1.13.1), [edge] Wmbusmeters (W-MBus to MQTT) (1.13.1-20)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 1
views | 10
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 3. Mai 2023 um 21:07
-- | --
current_recorder_run | 13. Mai 2023 um 19:43
estimated_db_size | 911.00 MiB
database_engine | sqlite
database_version | 3.40.1

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/killer0071234/ha-hiq/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Controller model

- [X] Cybro-2
- [ ] Cybro-3

### Describe the issue

After adding a new hiq device there are every 2nd update cycle all entities in invalid state.
the cause seems to be generated by the diagnostic sensor for the IP and port of the controller. 

### Reproduction steps

1. just add a new hiq instance with default parameters

### Debug logs

```text
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.hiq
Source: components/sensor/__init__.py:583
Integration: HIQ-Home (documentation, issues)
First occurred: 19:44:06 (221 occurrences)
Last logged: 20:58:31

Unexpected error fetching hiq data: Sensor sensor.c12762_sys_ip_port has device class None, state class None unit and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value: 192.168.1.20:8442 (<class 'str'>)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 581, in state
    numerical_value = float(value)  # type:ignore[arg-type]
ValueError: could not convert string to float: '192.168.1.20:8442'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/hiq/coordinator.py", line 68, in _async_update_data
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 146, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 406, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 649, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 591, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 583, in state
    raise ValueError(
ValueError: Sensor sensor.c12762_sys_ip_port has device class None, state class None unit  and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value: 192.168.1.20:8442 (<class 'str'>)
```

**Comment by killer0071234** [comment]
Disable of 'cXXX._sys_ip_port' will fix the fault temporary
